/** Rótulos amigáveis para colunas (snake_case da planilha / API). */
const MAP: Record<string, string> = {
  _registro: 'Evento',
  tipo: 'Tipo',
  cliente: 'Cliente',
  logomarca: 'Logomarca',
  num_ret: 'Nº ret.',
  consultor: 'Consultor',
  gerente: 'Gerente',
  area_ini: 'Área inicial',
  area_atend: 'Área atendimento',
  tipo_cha: 'Tipo chamado',
  bancada_atend: 'Bancada',
  data_abre: 'Abertura',
  hrs_orc: 'Hrs orç.',
  hrs_efe: 'Hrs efet.',
  cob_aprov: 'Cob. aprov.',
  dias: 'Dias',
  user_suporte: 'Usuário suporte',
  sta_ativ: 'Status',
  nota: 'Nota',
  categoria: 'Categoria',
  tipo_prob: 'Tipo problema',
  data_enc_agro: 'Enc. Agro',
  data_enc_cli: 'Enc. cliente',
  mes: 'Mês',
  ano: 'Ano',
  mes_num: 'Mês (núm.)',
  data_enc_ativ: 'Enc. atividade',
  cha_int: 'Chamado int.',
  grupo: 'Grupo',
  user_cliente: 'Usuário cliente',
  titulo: 'Título',
  data_sla: 'Data SLA',
  prioridade: 'Prioridade',
  tipo_prior: 'Tipo prior.',
  vlr_prior: 'Valor prior.',
  data_ult_ret: 'Últ. retorno',
  area_mae: 'Área mãe',
  nivel_atend: 'Nível atend.',
  qttransf: 'Qtd. transf.',
  hrsreal: 'Hrs reais',
  motivo_ins: 'Motivo inst.',
}

export function labelCampoChamado(campo: string): string {
  return MAP[campo] ?? campo.replace(/_/g, ' ')
}
